In [1]:
import numpy as np # importing the numpy module as np

In [2]:
arr_1d=np.array([1,2,3,4]) # creating the 1D array using numpy
print(arr_1d)# printing the array

[1 2 3 4]


In [3]:
arr_2d=np.array([[1,2,3,4],[5,6,7,8]]) # creating the 2D array
print(arr_2d)

[[1 2 3 4]
 [5 6 7 8]]


In [4]:
arr_2d.ndim # to check the dimention of the array so its an 2D array

2

In [5]:
arr_2d.size# to check the size of the array here the outcome is num of element

8

In [6]:
arr_2d.shape# to check the shape of the array here the out come is(row,colum)

(2, 4)

In [7]:
type(arr_2d) # to check the type of the variable

numpy.ndarray

In [8]:
arr_2d.dtype # to check the datatype of the elements in the list it show int that impiles the element are type int

dtype('int32')

In [9]:
ones_mt=np.ones((3,3),dtype=int) # creating the matrix which contains only 1 as there values and dtype changes the data type of the vales
print(ones_mt)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [10]:
zeros_mt=np.zeros((3,3),dtype=int) # cerating the matrix of values = zeros
print(zeros_mt)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [11]:
empty_mt=np.empty((3,3),dtype=int) # this creates an matrix of random elements 
print(empty_mt)

[[      0       1       0]
 [5570652     820       0]
 [    768       0      49]]


In [12]:
arr_arange=np.arange(0,10,2) # creates the 1Darray using the given range 
print(arr_arange)# syntax of the arange fuction is np.arange(start,end,num of gap b/w element)

[0 2 4 6 8]


In [13]:
arr_linspace=np.linspace(0,20,10) # creates the 1D array using the given range 
print(arr_linspace)# syntax is np.linspace(start,end,number of element)

[ 0.          2.22222222  4.44444444  6.66666667  8.88888889 11.11111111
 13.33333333 15.55555556 17.77777778 20.        ]


In [14]:
arr_reshape=np.arange(0,20,2).reshape(5,2) # here reshape function will change the shape of the arr to the given dimention
print(arr_reshape) # syntax is arr_name.reshape((dimention))

[[ 0  2]
 [ 4  6]
 [ 8 10]
 [12 14]
 [16 18]]


In [15]:
arr_transpose=arr_reshape.transpose() # this fuction will creat the transpose of the given matrix
print(arr_transpose)# syntax is arr_name.transpose()
arr_T=arr_transpose.T#

[[ 0  4  8 12 16]
 [ 2  6 10 14 18]]


In [16]:
arr_ravel=arr_transpose.ravel() # this ravel is used to create the 1D array from any ndim array
print(arr_ravel) #syntax is arr_name.ravel()
arr_flatten=arr_reshape.flatten() # flatten also gives the same results as ravel
print(arr_flatten)# syntax arr_name.flatten()

[ 0  4  8 12 16  2  6 10 14 18]
[ 0  2  4  6  8 10 12 14 16 18]


In [17]:
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2=np.array([[7,8,9],[4,5,6],[1,2,3]])
print(arr1+arr2,'\n',np.add(arr1,arr2)) # adding of the 2 array
print(arr1-arr2,'\n',np.subtract(arr1,arr2))# subtracting of 2 array
print(arr1*arr2,'\n',np.multiply(arr1,arr2))# multipling the 2 array
print(arr1/arr2,'\n',np.divide(arr1,arr2))# divide the 2 array
print(arr1.max()) # to find the max of the array
print(arr1.max(axis=1)) # to find max of rows 
print(arr1.min(axis=1))#to find min of row
print(arr1.argmax()) # to find the index of max value
print(arr1.argmin())# to find the index of minimum
print(np.mean(arr1))# to find the mean of the array
print(np.log(arr1))# to find the log of the array
print(np.sqrt(arr1))# to find the squart root of the array
print(np.exp(arr1))# to find the exp of the array


[[ 8 10 12]
 [ 8 10 12]
 [ 8 10 12]] 
 [[ 8 10 12]
 [ 8 10 12]
 [ 8 10 12]]
[[-6 -6 -6]
 [ 0  0  0]
 [ 6  6  6]] 
 [[-6 -6 -6]
 [ 0  0  0]
 [ 6  6  6]]
[[ 7 16 27]
 [16 25 36]
 [ 7 16 27]] 
 [[ 7 16 27]
 [16 25 36]
 [ 7 16 27]]
[[0.14285714 0.25       0.33333333]
 [1.         1.         1.        ]
 [7.         4.         3.        ]] 
 [[0.14285714 0.25       0.33333333]
 [1.         1.         1.        ]
 [7.         4.         3.        ]]
9
[3 6 9]
[1 4 7]
8
0
5.0
[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]
 [1.94591015 2.07944154 2.19722458]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]
[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]


In [18]:
arr3=np.random.rand(5,5) # creating the matrix of random elements
print(arr3)
print(arr3[0,0]) # calling the 0th row and 0th column element
print(arr3[0:3,0:3]) # sciling of the array, here row is 0 to 2nd and column is 0th to 2nd

[[0.99853635 0.80213602 0.86331637 0.89974515 0.84434881]
 [0.36770879 0.72142426 0.95926212 0.46532674 0.90556959]
 [0.80496566 0.7342925  0.99930082 0.42839618 0.3750381 ]
 [0.65733813 0.60419197 0.00335458 0.17234629 0.26088439]
 [0.69744548 0.81374261 0.26131127 0.77650145 0.59277428]]
0.9985363490434229
[[0.99853635 0.80213602 0.86331637]
 [0.36770879 0.72142426 0.95926212]
 [0.80496566 0.7342925  0.99930082]]


In [30]:
arr_concat=np.concatenate((arr1,arr2))# joing the 2 array
print(arr_concat)
arr_concat1=np.vstack((arr1,arr2)) # vertical concatinate
arr_concat2=np.hstack((arr1,arr2))# horisantal concatenate
print(arr_concat1,arr_concat2)
# spliting
print(np.split(arr1,[1,2])) # spliting the exsiting array it gives the list of array 

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [7 8 9]
 [4 5 6]
 [1 2 3]]
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [7 8 9]
 [4 5 6]
 [1 2 3]] [[1 2 3 7 8 9]
 [4 5 6 4 5 6]
 [7 8 9 1 2 3]]
[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


In [31]:
# trignometric function on the array
print(np.sin(arr1)) # using the sin function similarly we can use other fubctions also like tan cos etc

[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]
 [ 0.6569866   0.98935825  0.41211849]]


In [41]:
arr4=np.random.random((3,3)).ravel()
print(arr4)
print(np.random.choice(arr4)) # this function choies romdamly a element in the function
print(np.random.permutation(arr4))# this function will rearange the elements in the randam manner 

[0.69209158 0.21365075 0.69612563 0.00432253 0.79681951 0.83382546
 0.86146228 0.81290274 0.4045585 ]
0.6920915804756116
[0.86146228 0.21365075 0.83382546 0.69612563 0.00432253 0.79681951
 0.81290274 0.4045585  0.69209158]


In [66]:
# string operation in the numpy
str1='loko'
str2='esh'
np.char.add(str1,str2) # adding of the 2 string 
np.char.lower(str1)# to lower the case of the string
np.char.upper(str1) # to upper the case of the string
np.char.center(np.char.upper(np.char.add(str1,str2)),60,'*') # to print the srting in the center of the list syntax np.char.center(str,len,figure to be filled)
np.char.split(str1)
np.char.join([':'],str1)# to join the particular character in between the string
np.char.replace(str1,'l','A') # to replace the l letter with A
np.char.count(str1,'l') # to give the num of times l has occcured
np.char.equal(str1,str2)# to compare the strings are equal or not
np.char.find(str1,'o') # find the o in str1 it gives the index of the element

array(1)